# Generated by Django 6.0.4 on 2026-05-04 18:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('menu', '0002_alter_menuitemaddon_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyAnalytics',
            fields=[
                ('analyticsId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('hour', models.PositiveIntegerField(help_text='Hour of day (0-23)')),
                ('revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('orderCount', models.PositiveIntegerField(default=0)),
                ('averageOrderValue', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('itemsSold', models.PositiveIntegerField(default=0)),
                ('popularItems', models.JSONField(default=list, help_text='Top 5 items sold this hour')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hourly Analytics',
                'verbose_name_plural': 'Hourly Analytics',
                'db_table': 'hourly_analytics',
                'ordering': ['-date', '-hour'],
                'unique_together': {('date', 'hour')},
            },
        ),
        migrations.CreateModel(
            name='SalesSummary',
            fields=[
                ('summaryId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('periodType', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], max_length=10)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('totalRevenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('totalOrders', models.PositiveIntegerField(default=0)),
                ('averageOrderValue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('totalItemsSold', models.PositiveIntegerField(default=0)),
                ('uniqueItemsSold', models.PositiveIntegerField(default=0)),
                ('cashPayments', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cardPayments', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('otherPayments', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('topStaff', models.JSONField(default=dict, help_text='Staff performance data')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sales Summary',
                'verbose_name_plural': 'Sales Summaries',
                'db_table': 'sales_summary',
                'ordering': ['-startDate'],
                'unique_together': {('periodType', 'startDate', 'endDate')},
            },
        ),
        migrations.CreateModel(
            name='InventoryAnalytics',
            fields=[
                ('analyticsId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('startingStock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('endingStock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stockUsed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costOfGoodsSold', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('averageCostPerUnit', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('stockTurnover', models.DecimalField(decimal_places=2, default=0.0, help_text='How many times stock was replaced', max_digits=5)),
                ('wastePercentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('inventoryItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='inventory.inventoryitem')),
            ],
            options={
                'verbose_name': 'Inventory Analytics',
                'verbose_name_plural': 'Inventory Analytics',
                'db_table': 'inventory_analytics',
                'ordering': ['-date'],
                'unique_together': {('inventoryItem', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ItemPerformance',
            fields=[
                ('performanceId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('quantitySold', models.PositiveIntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('orderCount', models.PositiveIntegerField(default=0)),
                ('salesRank', models.PositiveIntegerField(default=0, help_text='Rank among all items that day')),
                ('popularityScore', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('menuItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='menu.menuitem')),
            ],
            options={
                'verbose_name': 'Item Performance',
                'verbose_name_plural': 'Item Performance',
                'db_table': 'item_performance',
                'ordering': ['-date', '-quantitySold'],
                'unique_together': {('menuItem', 'date')},
            },
        ),
        migrations.CreateModel(
            name='StaffPerformance',
            fields=[
                ('performanceId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('ordersTaken', models.PositiveIntegerField(default=0)),
                ('ordersServed', models.PositiveIntegerField(default=0)),
                ('totalRevenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('hoursWorked', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('averageOrderTime', models.DecimalField(decimal_places=2, default=0.0, help_text='Minutes per order', max_digits=6)),
                ('customerSatisfaction', models.DecimalField(decimal_places=1, default=0.0, help_text='1-5 rating', max_digits=3)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Performance',
                'verbose_name_plural': 'Staff Performance',
                'db_table': 'staff_performance',
                'ordering': ['-date', '-totalRevenue'],
                'unique_together': {('staff', 'date')},
            },
        ),
    ]
