# Generated by Django 6.0.4 on 2026-05-04 18:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('menu', '0002_alter_menuitemaddon_options'),
        ('orders', '0004_customer_order_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_low_stock', models.BooleanField(default=True)),
                ('notify_out_of_stock', models.BooleanField(default=True)),
                ('notify_orders', models.BooleanField(default=True)),
                ('notify_payments', models.BooleanField(default=True)),
                ('notify_system', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=False)),
                ('email_low_stock', models.BooleanField(default=False)),
                ('low_stock_alert_days', models.IntegerField(default=1, help_text='Alert when stock will last this many days')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
                'db_table': 'notification_preference',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notificationId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('LowStock', 'Low Stock Alert'), ('OutOfStock', 'Out Of Stock'), ('OrderPlaced', 'Order Placed'), ('OrderCompleted', 'Order Completed'), ('OrderCancelled', 'Order Cancelled'), ('PaymentReceived', 'Payment Received'), ('PaymentPending', 'Payment Pending'), ('CreditApproved', 'Credit Approved'), ('SystemError', 'System Error')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('Unread', 'Unread'), ('Read', 'Read'), ('Archived', 'Archived')], default='Unread', max_length=15)),
                ('priority', models.IntegerField(default=1, help_text='1=Low, 5=Critical')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('readAt', models.DateTimeField(blank=True, null=True)),
                ('inventoryItem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='inventory.inventoryitem')),
                ('menuItem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='menu.menuitem')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='orders.order')),
                ('targetAdmin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notification',
                'ordering': ['-createdAt'],
                'indexes': [models.Index(fields=['-createdAt'], name='notificatio_created_df01bb_idx'), models.Index(fields=['status'], name='notificatio_status_700f9c_idx'), models.Index(fields=['type'], name='notificatio_type_f65c28_idx')],
            },
        ),
    ]
