# Generated by Django 6.0.4 on 2026-05-04 15:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('isActive', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('menuItemId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('itemType', models.CharField(choices=[('Food', 'Food'), ('Drink', 'Drink'), ('Combo', 'Combo'), ('Other', 'Other')], default='Food', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_images/')),
                ('isAvailable', models.BooleanField(default=True)),
                ('trackStock', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menuItems', to='menu.category')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
                'db_table': 'menu_item',
            },
        ),
        migrations.CreateModel(
            name='MenuItemAddon',
            fields=[
                ('addonId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('extraPrice', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('isAvailable', models.BooleanField(default=True)),
                ('menuItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='menu.menuitem')),
            ],
            options={
                'verbose_name': 'Menu Item Addon',
                'verbose_name_plural': 'Menu Item Addons',
                'db_table': 'menu_item_addon',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stockId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('lowStockThreshold', models.PositiveIntegerField(default=10, help_text='Alert when stock falls below this')),
                ('unit', models.CharField(default='units', help_text='e.g. units, kg, litres, plates', max_length=50)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('menuItem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='menu.menuitem')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stock',
                'db_table': 'stock',
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('transactionId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transactionType', models.CharField(choices=[('Restock', 'Restock'), ('Sale', 'Sale'), ('Adjustment', 'Manual Adjustment'), ('Wastage', 'Wastage')], max_length=15)),
                ('quantityChanged', models.IntegerField(help_text='Positive for additions, negative for deductions')),
                ('quantityBefore', models.PositiveIntegerField()),
                ('quantityAfter', models.PositiveIntegerField()),
                ('note', models.TextField(blank=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('performedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stockTransactions', to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='menu.stock')),
            ],
            options={
                'verbose_name': 'Stock Transaction',
                'verbose_name_plural': 'Stock Transactions',
                'db_table': 'stock_transaction',
                'ordering': ['-createdAt'],
            },
        ),
    ]
