# Generated by Django 6.0.4 on 2026-05-04 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitemaddon',
            options={'verbose_name': 'Menu Item Addon'},
        ),
    ]
