# Generated by Django 6.0.4 on 2026-05-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menuitemaddon_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
