# Generated by Django 6.0.4 on 2026-05-04 15:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('inventoryItemId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(choices=[('kg', 'Kilograms'), ('g', 'Grams'), ('L', 'Litres'), ('ml', 'Millilitres'), ('units', 'Units'), ('bags', 'Bags'), ('cartons', 'Cartons'), ('bottles', 'Bottles'), ('packs', 'Packs')], default='units', max_length=10)),
                ('quantityInStock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('lowStockThreshold', models.DecimalField(decimal_places=2, default=5, max_digits=10)),
                ('costPerUnit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('isActive', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inventory Item',
                'verbose_name_plural': 'Inventory Items',
                'db_table': 'inventory_item',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplierId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('contactName', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('isActive', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'db_table': 'supplier',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('purchaseOrderId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('poNumber', models.CharField(editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Ordered', 'Ordered'), ('Received', 'Received'), ('Cancelled', 'Cancelled')], default='Draft', max_length=15)),
                ('totalCost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('note', models.TextField(blank=True)),
                ('orderedAt', models.DateTimeField(blank=True, null=True)),
                ('receivedAt', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('orderedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchaseOrders', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchaseOrders', to='inventory.supplier')),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'db_table': 'purchase_order',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('transactionId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transactionType', models.CharField(choices=[('Purchase', 'Purchase'), ('Usage', 'Usage'), ('Adjustment', 'Adjustment'), ('Wastage', 'Wastage'), ('Return', 'Return')], max_length=15)),
                ('quantityChanged', models.DecimalField(decimal_places=2, help_text='Positive = added, Negative = removed', max_digits=10)),
                ('quantityBefore', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantityAfter', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.TextField(blank=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('inventoryItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.inventoryitem')),
                ('performedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventoryTransactions', to=settings.AUTH_USER_MODEL)),
                ('relatedOrder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventoryTransactions', to='orders.order')),
                ('relatedPO', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventoryTransactions', to='inventory.purchaseorder')),
            ],
            options={
                'verbose_name': 'Inventory Transaction',
                'verbose_name_plural': 'Inventory Transactions',
                'db_table': 'inventory_transaction',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('poItemId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantityOrdered', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantityReceived', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costPerUnit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lineTotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('inventoryItem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchaseItems', to='inventory.inventoryitem')),
                ('purchaseOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.purchaseorder')),
            ],
            options={
                'verbose_name': 'Purchase Order Item',
                'verbose_name_plural': 'Purchase Order Items',
                'db_table': 'purchase_order_item',
            },
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventoryItems', to='inventory.supplier'),
        ),
        migrations.CreateModel(
            name='MenuItemIngredient',
            fields=[
                ('ingredientId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantityUsed', models.DecimalField(decimal_places=3, help_text='Amount used per serving', max_digits=10)),
                ('inventoryItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usedIn', to='inventory.inventoryitem')),
                ('menuItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='menu.menuitem')),
            ],
            options={
                'verbose_name': 'Menu Item Ingredient',
                'verbose_name_plural': 'Menu Item Ingredients',
                'db_table': 'menu_item_ingredient',
                'unique_together': {('menuItem', 'inventoryItem')},
            },
        ),
    ]
