# Generated by Django 6.0.4 on 2026-05-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_pocounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
