# Generated by Django 6.0.4 on 2026-05-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventoryitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='costPerUnit',
            field=models.FloatField(default=0.0),
        ),
    ]
