# Generated by Django 6.0.4 on 2026-05-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_menuitem_remove_staff_isactive_alter_staff_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postransaction',
            name='item',
        ),
        migrations.RemoveField(
            model_name='postransaction',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='pin',
        ),
        migrations.AddField(
            model_name='staff',
            name='failedPinAttempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='staff',
            name='lastLoginAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('Administrator', 'Administrator'), ('Clerk', 'Clerical staff'), ('InventoryManager', 'Inventory Manager'), ('Kitchen', 'Kitchen Staff')], default='Clerk', max_length=25),
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
        migrations.DeleteModel(
            name='PosTransaction',
        ),
    ]
