# Generated by Django 6.0.4 on 2026-05-04 15:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('orderNumber', models.CharField(editable=False, max_length=20, unique=True)),
                ('orderType', models.CharField(choices=[('DineIn', 'Dine In'), ('Takeaway', 'Takeaway'), ('Delivery', 'Delivery')], default='DineIn', max_length=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Preparing', 'Preparing'), ('Ready', 'Ready'), ('Served', 'Served'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=15)),
                ('paymentStatus', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid'), ('Partial', 'Partial Payment'), ('Refunded', 'Refunded')], default='Unpaid', max_length=10)),
                ('tableNumber', models.CharField(blank=True, help_text='For dine-in orders', max_length=10, null=True)),
                ('customerName', models.CharField(blank=True, max_length=200)),
                ('customerPhone', models.CharField(blank=True, max_length=20)),
                ('note', models.TextField(blank=True, help_text='Special instructions')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('discountAmount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('taxAmount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('totalAmount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('completedAt', models.DateTimeField(blank=True, null=True)),
                ('servedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordersServed', to=settings.AUTH_USER_MODEL)),
                ('takenBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordersTaken', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'order',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('orderItemId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unitPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lineTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.TextField(blank=True, help_text='e.g. no onions, extra spicy')),
                ('menuItem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orderItems', to='menu.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'db_table': 'order_item',
            },
        ),
        migrations.CreateModel(
            name='OrderItemAddon',
            fields=[
                ('orderItemAddonId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('extraPrice', models.DecimalField(decimal_places=2, max_digits=8)),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.menuitemaddon')),
                ('orderItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selectedAddons', to='orders.orderitem')),
            ],
            options={
                'db_table': 'order_item_addon',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('paymentId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Transfer', 'Bank Transfer'), ('MobileMoney', 'Mobile Money'), ('Split', 'Split Payment')], max_length=15)),
                ('amountPaid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amountChange', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('reference', models.CharField(blank=True, help_text='Transaction ref for transfers/card', max_length=100)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
                ('processedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paymentsProcessed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payment',
            },
        ),
    ]
