# Generated by Django 6.0.4 on 2026-05-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_ordercounter_receiptcounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paymentMethod',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Transfer', 'Bank Transfer'), ('MobileMoney', 'Mobile Money'), ('Split', 'Split Payment')], max_length=15, null=True),
        ),
    ]
