# Generated by Django 6.0.4 on 2026-05-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_paymentmethod'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ['-generatedAt']},
        ),
        migrations.AddField(
            model_name='order',
            name='inventory_deducted',
            field=models.BooleanField(default=False, help_text='Set True after inventory has been deducted — prevents repeat deduction on re-save.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='tableNumber',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='verificationStatus',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Rejected', 'Rejected')], default='Confirmed', max_length=10),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='isDigitallySent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='printCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receiptHTML',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receiptText',
            field=models.TextField(blank=True),
        ),
    ]
