# Generated by Django 6.0.4 on 2026-05-10 00:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('unit', models.CharField(choices=[('kg', 'Kilograms'), ('g', 'Grams'), ('L', 'Litres'), ('ml', 'Millilitres'), ('units', 'Units'), ('bags', 'Bags'), ('cartons', 'Cartons'), ('bottles', 'Bottles'), ('packs', 'Packs'), ('crates', 'Crates'), ('pieces', 'Pieces')], default='units', max_length=10)),
                ('current_quantity', models.FloatField(default=0)),
                ('low_stock_threshold', models.FloatField(default=0)),
                ('default_usage_quantity', models.FloatField(default=0, help_text='Typical amount used per usage')),
                ('note', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'store_item',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StoreTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('received', 'Received'), ('used', 'Used'), ('damaged', 'Damaged'), ('adjusted', 'Adjusted')], max_length=20)),
                ('quantity', models.FloatField(help_text='Always positive; direction determined by transaction_type')),
                ('quantity_before', models.FloatField()),
                ('quantity_after', models.FloatField()),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='store.storeitem')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'store_transaction',
                'ordering': ['-created_at'],
            },
        ),
    ]
