# Generated by Django 6.0.4 on 2026-05-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='units_per_item',
            field=models.FloatField(default=1.0, help_text='How many usage units fit in one stock unit (e.g. 20 cups per bag)'),
        ),
        migrations.AddField(
            model_name='storeitem',
            name='usage_unit',
            field=models.CharField(choices=[('cups', 'Cups'), ('scoops', 'Scoops'), ('ml', 'Millilitres'), ('g', 'Grams'), ('pieces', 'Pieces'), ('servings', 'Servings'), ('L', 'Litres'), ('tablespoons', 'Tablespoons'), ('units', 'Units')], default='units', help_text='Unit used when consuming this item (e.g. cups, scoops)', max_length=20),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='default_usage_quantity',
            field=models.FloatField(default=0, help_text='Default amount (in usage_unit) consumed per transaction'),
        ),
    ]
