name: Build & Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Inject token
        run: echo GITHUB_TOKEN = "${{ secrets.GH_TOKEN_UPDATER }}" > config.py

      - name: Install deps
        run: |
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build exe
        run: |
          cd Administrator
          python -m PyInstaller --noconfirm --onefile --windowed --icon="Roes.ico" --name "roes-admin" admin_app.py

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/roes-admin.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
